test: add a test for the request
genshin-kit/genshin-kit-node pull request #42
Opened 2021-09-15 07:57 UTC by ChanIok

添加request.ts模块的测试，通过命令行输入cookie
例如：
npm run test --cookie "你的cookie"

2021-09-15 12:21 UTC, ChanIok commented
将`` core/package.json ``的
`  "ts-node": "^10.2.1",
    "@types/node": "^16.7.12",
    "typescript": "^4.4.3"`
转移到了根目录下的`` package.json ``

2021-09-15 13:02 UTC, Dragon-Fish commented
1. 建议包管理器使用 `yarn` 避免 lock 文件混乱
2. 可以通过环境变量传入 cookie 吗，这样显得更为优雅

2021-09-15 14:04 UTC, ChanIok commented
> 建议包管理器使用 yarn 避免 lock 文件混乱
> 可以通过环境变量传入 cookie 吗，这样显得更为优雅

1. 已转为yarn
2. 通过环境变量传入`` cookie  ``没想到怎么实现比较好。例如将`` cookie ``写入`` package.json ``文件中来传入环境变量，会使得开发者的`` cookie ``暴露在仓库当中；或者单独使用一个文件保存`` cookie ``，忽略它的上传，这也使得别的开发者需要重新创建文件才能测试。通过命令行传入是较为安全的做法，这里的Actions也是如此实现。

2021-09-15 15:23 UTC, ChanIok commented
> 通过环境变量传入cookie 
在大佬的建议下已改为通过系统环境变量传入cookie

2021-09-17 01:03 UTC, Dragon-Fish requested changes

2021-09-17 01:04 UTC, Dragon-Fish commented
请不要重命名现有模块与配置文件。

2021-09-17 06:36 UTC, ChanIok commented
1. 感谢大佬指点，已使用``` yarn workspace @genshin-kit/core run test ```
2. 已回退所有非测试相关文件，但由于该仓库中模块的名字 ` characterNickname.ts `与 ` index.ts ` 中导入的不一样，会导致actions运行出错 ``` Cannot find module './CharacterNickname' or its corresponding type declarations. ```

2021-11-21 17:08 UTC, merged